### ISSUE TITLE
AsyncOperation does not update .progress of OperationQueue when finished

### ISSUE THREAD

**Issue by ghowen** [radianttap/Swift-Essentials#5]
I have just implemented your `AsyncOperation` in a project and it worked like a charm - until I started to use the new `.progress` property of `OperationQueue` (introduced with iOS 13).  

I found out the hard way that you need to increase the `.totalUnitCount` of `OperationQueue` manually (https://stackoverflow.com/questions/60741067/progress-property-of-operationqueue-not-working-in-ios-13) when adding operations to the queue. But with this progress reporting started to work well - except for subclasses of AsyncOperation. 

The `.finished()` method does get called on all subclasses of AsyncOperation, but somehow the `.progress` of the OperationQueue does not get the information about the finished task. The `.operationCount` of the queue decreases and the operations are removed from the `[operations]`. So in general AsyncOperation works. But the info about a finished operation is not signaled to the queue in a way that it can reflect this in its `.progress` property.

I am a bit at a loss here myself as I have no idea how iOS monitors this, so I really don't expect a quick fix. But I thought I'd let you know about this. 

Thanks for your work!

**Comment by radianttap** [comment]
This is first time I hear about the progress property, thanks for letting me know. Feel free to fork and play with it – I'll be very happy to accept pull requests for this.

**Comment by ghowen** [comment]
Thanks. After a good night's sleep it wasn't so hard to figure out: https://github.com/radianttap/Swift-Essentials/pull/6 fixes this.

**Comment by radianttap** [comment]
Will need to investigate some other solution (see my comment on the PR 6).

**Comment by ghowen** [comment]
OK. There seems to be a conflict between two official documentations :) The developer docs and the comment from Apple in the NSOperation.h.

**Comment by radianttap** [comment]
I'll to revisit my start method override, do I even need it.

**Comment by ghowen** [comment]
I filed a feedback with Apple to see what they have to say about this. I'll let you know once I know.

**Comment by radianttap** [comment]
Try with the version I just pushed (for history: [this commit](https://github.com/radianttap/Swift-Essentials/commit/3ffc3c400bb9ed66ab02824988f703e94f42f06c)).

Completely different internals, start is not overriden, just `main()` and `isFinished`.

**Comment by radianttap** [comment]
Also, please do a test run with Thread Sanitizer enabled, on whatever project you are using this.

**Comment by ghowen** [comment]
Nice one! Works fine in the test project where I was troubleshooting the progress as well as in the actual project (upcoming release of https://anyfinder.info). 

No complaints from Thread Sanitizer in either project.

Thanks!

**Comment by radianttap** [comment]
I also tested this in two largest projects I have, which are both using Operations for networking and data storage. TSan reports no issues and anything I tried worked fine.

I suspect a large part of this working properly is due to [KVO improvements done in Swift itself](https://github.com/apple/swift/pull/20103). I'll keep an eye on this in future projects.

**Comment by ghowen** [comment]
Not sure if this is related to the change but I am now getting a crash at another point in the app that also uses the queue.

It's a 

`Thread 3: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0) *** -[NSKeyValueObservance retain]: message sent to deallocated instance 0x6000013bdc50` 

exception and when I trace it back in the call stack I land at

`        didChangeValue(forKey: "isFinished")
`

![Bildschirmfoto 2020-03-30 um 14 03 26](https://user-images.githubusercontent.com/390784/77915355-40b95900-728f-11ea-8dab-50d3ef84409d.png)

**Comment by ghowen** [comment]
https://github.com/radianttap/Swift-Essentials/issues/5#issuecomment-605986472 is not related. My bad.
